import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QLabel, QPushButton
from PyQt5 import QtCore, QtWidgets, QtGui

class Ui_start_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_screen = QtWidgets.QLabel(self.centralwidget)
        self.image_screen.setGeometry(QtCore.QRect(-30, -30, 930, 539))
        self.image_screen.setText("")
        self.image_screen.setPixmap(QtGui.QPixmap("Other/image.png"))
        self.image_screen.setObjectName("image_screen")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(44, 470, 170, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setStyleSheet("color: white;")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 15, 170, 460))
        self.frame.setStyleSheet("border-radius: 10px;")
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profit_tree_pushButton = QtWidgets.QPushButton(self.frame)
        self.profit_tree_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profit_tree_pushButton.sizePolicy().hasHeightForWidth())
        self.profit_tree_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.profit_tree_pushButton.setFont(font)
        self.profit_tree_pushButton.setMouseTracking(False)
        self.profit_tree_pushButton.setTabletTracking(False)
        self.profit_tree_pushButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(63, 120, 115, 255), stop:1 rgba(39, 0, 75, 255));\n""")
        self.profit_tree_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.profit_tree_pushButton.setCheckable(False)
        self.profit_tree_pushButton.setChecked(False)
        self.profit_tree_pushButton.setAutoDefault(False)
        self.profit_tree_pushButton.setDefault(False)
        self.profit_tree_pushButton.setFlat(False)
        self.profit_tree_pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.profit_tree_pushButton)
        self.prices_pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prices_pushButton.sizePolicy().hasHeightForWidth())
        self.prices_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.prices_pushButton.setFont(font)
        self.prices_pushButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(63, 120, 115, 255), stop:1 rgba(39, 0, 75, 255));")
        self.prices_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.prices_pushButton.setCheckable(False)
        self.prices_pushButton.setChecked(False)
        self.prices_pushButton.setAutoDefault(False)
        self.prices_pushButton.setDefault(False)
        self.prices_pushButton.setFlat(False)
        self.prices_pushButton.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.prices_pushButton)
        self.Discord_pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Discord_pushButton.sizePolicy().hasHeightForWidth())
        self.Discord_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Discord_pushButton.setFont(font)
        self.Discord_pushButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(63, 120, 115, 255), stop:1 rgba(39, 0, 75, 255));")
        self.Discord_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.Discord_pushButton.setCheckable(False)
        self.Discord_pushButton.setChecked(False)
        self.Discord_pushButton.setAutoDefault(False)
        self.Discord_pushButton.setDefault(False)
        self.Discord_pushButton.setFlat(False)
        self.Discord_pushButton.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.Discord_pushButton)
        self.statistics_pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statistics_pushButton.sizePolicy().hasHeightForWidth())
        self.statistics_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.statistics_pushButton.setFont(font)
        self.statistics_pushButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(63, 120, 115, 255), stop:1 rgba(39, 0, 75, 255));")
        self.statistics_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.statistics_pushButton.setCheckable(False)
        self.statistics_pushButton.setChecked(False)
        self.statistics_pushButton.setAutoDefault(False)
        self.statistics_pushButton.setDefault(False)
        self.statistics_pushButton.setFlat(False)
        self.statistics_pushButton.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.statistics_pushButton)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bot_status_label = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_status_label.sizePolicy().hasHeightForWidth())
        self.bot_status_label.setSizePolicy(sizePolicy)
        self.bot_status_label.setMinimumSize(QtCore.QSize(0, 0))
        self.bot_status_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bot_status_label.setFont(font)
        self.bot_status_label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(63, 120, 115, 255), stop:1 rgba(39, 0, 75, 255));")
        self.bot_status_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bot_status_label.setTextFormat(QtCore.Qt.AutoText)
        self.bot_status_label.setScaledContents(False)
        self.bot_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bot_status_label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.bot_status_label)
        self.active_label = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_label.sizePolicy().hasHeightForWidth())
        self.active_label.setSizePolicy(sizePolicy)
        self.active_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.active_label.setFont(font)
        self.active_label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(63, 120, 115, 255), stop:1 rgba(39, 0, 75, 255));\n""color: green;")
        self.active_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.active_label.setTextFormat(QtCore.Qt.AutoText)
        self.active_label.setScaledContents(False)
        self.active_label.setAlignment(QtCore.Qt.AlignCenter)
        self.active_label.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.active_label)
        self.verticalLayout.addWidget(self.frame1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Albion Statistics"))
        self.checkBox.setText(_translate("MainWindow", "Close after change"))
        self.profit_tree_pushButton.setText(_translate("MainWindow", "Profit Tree"))
        self.prices_pushButton.setText(_translate("MainWindow", "Prices"))
        self.Discord_pushButton.setText(_translate("MainWindow", "Disc - DB"))
        self.statistics_pushButton.setText(_translate("MainWindow", "Statistics"))
        self.bot_status_label.setText(_translate("MainWindow", "Bot Status"))
        self.active_label.setText(_translate("MainWindow", "Active"))




if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_start_window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
